- name: Install ufw application
  yum: name=ufw state=present

- name: Start ufw firewall service
  service: name=ufw state=started enabled=yes

- name: Disable firewalld service
  service: name=firewalld state=stopped enabled=no
  when: disable_alternative_firewall
